### ISSUE TITLE
Suggestion: Include shaders files in the examples and some helpful links referred to the current example

### ISSUE THREAD

**Issue by darilrt** [bevyengine/bevy-website#837] opened 2023-12-11 21:34 UTC

**Comment by TrialDragon** [comment] 2024-02-16 05:41
This appears to be a duplicate of #456 maybe?

**Comment by BD103** [comment] 2024-02-18 04:00
Yeah, this can be closed as a duplicate.

**Comment by IceSentry** [comment] 2024-02-18 20:54
Closed as duplicate of https://github.com/bevyengine/bevy-website/issues/456

**Closed by IceSentry** 2024-02-18 20:54 UTC
