### ISSUE TITLE
Example pages should include shader code

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy-website#1651] opened 2024-10-19 03:11 UTC
Many of the official Bevy examples involve custom shaders, and in some cases reading the Rust source code doesn't make much sense unless you also read the shader code. For example, it's hard to understand the array texture example without looking at the shader.

Unfortunately, while the website makes it easy to look at the example code, it's not at all obvious for the newcomer to find the corresponding shader code - they have to go to the bevy source tree in github, find the right folder, and browse the correct file.

What I would like to see is a way to include the shader code on the same page as the example. There are a number of ways this could be approached, such as having some embedded comment or tag in the rust source that tells the site generator to include additional files in the generated page.

**Comment by TrialDragon** [comment] 2024-10-19 03:48
This has already been implemented in #1434 and this issue a duplicate of #456 .

There are already code blocks showcasing the shader code for the examples that involve shaders. See this photo of the current web texture array example's shader code on the live site right now:
![Image](https://github.com/user-attachments/assets/b549dc37-d96f-4c72-9f96-94a10cbd05f6)

You just need to scroll down beyond the Rust code block slightly.

**Closed** 2024-10-19 03:49 UTC
Labels: S-Duplicate, A-Examples
