### ISSUE TITLE
Optional Bundle Members

### ISSUE THREAD

**Issue by Zeenobit** [bevyengine/bevy-website#759] opened 2023-10-14 00:49 UTC
As Bevy 0.11, this does not compile:
```rust
#[derive(Bundle)]
struct Foo {
    bar: Option<Bar>,
    ...
}

#[derive(Component)]
struct Bar;
```
This means it's impossible express bundles with "optional components". The workaround is to create distinct types for variations with/without the optional components:
```rust
#[derive(Bundle)]
struct Foo {
    ...
}


#[derive(Bundle)]
struct FooWithBar {
   bar: Bar,
   ...
}
```

Ideally, bundles should allow optional components/bundles as their members. This would eliminate some code duplication for the user and allow them to express optional components more explicitly and ergonomically.

During insertion, the bundle could check for `None` values and not insert those components.
During removal, the component would be removed if it exists, which I believe is already the existing behavior.

**Comment by alice-i-cecile** [comment] 2023-10-14 00:54
Duplicate of https://github.com/bevyengine/bevy/issues/2157 <3 This is the website for the book / release notes etc, not the engine, so that's probably why you didn't find the duplicate.

**Closed by alice-i-cecile** 2023-10-14 00:54 UTC
